spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hackathon?useUnicode=true&characterEncoding=utf-8&useSSL=true&useOldAliasMetadataBehavior=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
